### ISSUE TITLE
osxinstall does not ask if TA is installed / does not let to select dir. (+ some osxcmdinstall comentary)

### ISSUE THREAD

**Issue by sh1ku** [SwissKid/Tomoyo-After-Patch#1]
Trying to run the script, I get this:

103:109: syntax error: Expected end of line, etc. but found class name. (-2741)
button returned:Aceptar
57:130: execution error: System Events got an error: Can’t make alias "" into type alias. (-1700)
button returned:Aceptar
chmod: fts_open: No such file or directory
button returned:Aceptar
57:144: execution error: File alias --filename=~/.rlvm/ wasn’t found. (-43)
131:137: syntax error: Expected end of line, etc. but found class name. (-2741)
 could not be understood. Interpreting as 'no'
button returned:Aceptar

It throws the 103:109 exception, then skips the installation question
![screenshot 2013-09-09 01 22 44](https://f.cloud.github.com/assets/1584944/1104061/a6f782b8-18dd-11e3-9392-9a3e4a95000d.png)

After that, throws 57:130, and shows this dialog:
![captura de pantalla 2013-09-09 a la s 01 25 32](https://f.cloud.github.com/assets/1584944/1104068/8415f602-18de-11e3-8d1e-beec01028a5a.png)

It states that the script doesn't found the working dir (chmod: fts_open: No such file or directory) and shows this dialog:
![captura de pantalla 2013-09-09 a la s 01 26 19](https://f.cloud.github.com/assets/1584944/1104069/8db57db8-18de-11e3-9a43-2d9bcd52305e.png)

It throws 57:144 showing this error and an "Installation Cancelled" error dialog and then it shows it again after throwing 131:137.

(uploaded a youtube video explaining better the situation and explaining the osxcmdinstall bugs http://youtu.be/qgLCH48RvKw)

**Comment by SwissKid** [comment]
Alright, I'll wait for the vid. Like I said, it's very likely buggy on
OSX, since I don't know apple script that well, and couldn't debug it
before. If you have any scripting knowledge you can look at the script
and see if you can debug it. Elsewise, I'll patch it up and we can try
again :)

**Comment by sh1ku** [comment]
There we are, I can add subtitles to the video in order to make it easier to understand... Yeah, my spoken english kinda sucks xD. I "applescripted" a lot of times, but never combining shell and applescript. I'll take a look though!

**Comment by SwissKid** [comment]
I only wrote in the applescript as functions so that it could possibly
be used with the meat of the other script: so that I wrote one big
script that did all the important stuff, and an OS dependent function
script that did the stuff like "choose directory." 

Btw, if you want to put in a Spanish installer, you're welcome to
(though it'd be a bit silly with an english translated game :P )

**Comment by sh1ku** [comment]
I updated osxinstall to fix a bit the applescript code, but I still don't know why it has permission issues while applying the patches, and not when installing the game :/

**Comment by SwissKid** [comment]
Seems like you're getting most of the bugs out. If you can specify what's not working at this point I'll take a look.

**Comment by sh1ku** [comment]
Well, only thing that last to fix is the "Cancel" option (I don't know why the shell function "exit" does not work as intended...)

Screencaps ^^ 

![captura de pantalla 2013-09-09 a la s 05 43 43](https://f.cloud.github.com/assets/1584944/1104615/14866b18-1902-11e3-9e4c-8c380815b682.png)
![screenshot 2013-09-09 05 38 16](https://f.cloud.github.com/assets/1584944/1104606/cfd9d7fc-1901-11e3-847a-c9b09ffe9cf0.png)
![screenshot 2013-09-09 05 38 34](https://f.cloud.github.com/assets/1584944/1104608/d0066d1c-1901-11e3-9c85-6eefcb5dcac8.png)
![screenshot 2013-09-09 05 38 57](https://f.cloud.github.com/assets/1584944/1104607/cff58574-1901-11e3-9ca8-a23c86da4875.png)

**Comment by SwissKid** [comment]
Awesome, it looks like you've got it prettymuch working! I'm going to wait for another tester or two to go through the mac one before announcing it "working" but great job! 
When we do the release, if I want to credit you, what name would you like us to use?

**Comment by sh1ku** [comment]
Oh, that makes me happy, you can call me shiku, I usually use that nick, but well, I did almost nothing compared to you ^^. 

I'll go to sleep! See you later!
